POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2020-01-15",
  "description": "pizdiec",
  "specialist": "daktaras",
  "diagnosisCodes": ["Z123", "AAA"],
  "type": "HealthCheck",
  "healthCheckRating": 3
}
